services:
  app:
    build: .
    container_name: monitoringlele_ci
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: codeigniter_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monitoringlele
      MYSQL_USER: ci_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/monitoringlele.sql:/docker-entrypoint-initdb.d/monitoringlele.sql


volumes:
  db_data:
